network_id: 8964
contract_address: 'tNULSeBaMwVP6DSxnA8XqEfo3Ex4UjPy72e3VW'
reward_address: 'tNULSeBaMtymkUpfxjk9Ytr3LPEFqNyGSFSem8'
distribution_address: ''
source_address: ''
distribution_remark: 'ALEPH-POCM'
refund_remark: 'ALEPH-POCM-NODE'
distribution_pre_active_remark: 'ALEPH-POCM-ACTIVATION'
bulk_max_items: 120

mongodb_host: localhost
mongodb_port: 27017
mongodb_db: nuls2test

distribution_pkey: ''
airdrop_pkey: ''
source_pkey: ''