network_id: 8964
contract_address: 'NseL2yUZ8sJCPXTfL3MSGhdqLBhm7q3A'
reward_address: 'Nsdxm3zMQRdJDxgmu3DaLEphC2k1wJQK'
distribution_address: 'Nse1oQy8oHz3xqCCPACBtrUaCucF1xJ3'
source_address: 'NsdtremzA1ppwcfTgaLhkKRUGuWWAMjz'
distribution_remark: 'ALEPH-POCM'
refund_remark: 'ALEPH-POCM-NODE'
bulk_max_items: 120

distribution_pkey: ''
airdrop_pkey: ''
source_pkey: ''