network_id: 261
contract_address: 'TTbE8y7mudKhuU3yoeLNR59mgkrspo7T'
reward_address: 'TTaxGYRaCLYwiZgQKqqhxdyA1gRNyDuN'
distribution_address: 'TTakCvQJwY5qPWRWShB5pqLJJgpHMrUE'
source_address: 'TTaq39KYE5DAfHC81w8yNKepaKP9GTXD'
distribution_remark: 'ALEPH-POCM'
refund_remark: 'ALEPH-POCM-NODE'
bulk_max_items: 120

distribution_pkey: ''
airdrop_pkey: ''